# Generated by Django 4.2.4 on 2023-09-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=220)),
                ('first_name', models.CharField(max_length=220)),
                ('mobilenum', models.CharField(max_length=220)),
                ('password', models.CharField(max_length=220)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
