# Generated by Django 4.2.4 on 2023-09-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_customer_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobilenum',
            new_name='mobile_number',
        ),
    ]
