# Generated by Django 4.2.2 on 2023-10-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_remove_product_product_image_category_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer',
            new_name='cuostomer',
        ),
    ]
