# Generated by Django 4.2.4 on 2023-10-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_rename_customer_cuostomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuostomer',
            name='username',
            field=models.CharField(max_length=220, unique=True),
        ),
    ]
