# Generated by Django 4.2.4 on 2023-10-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_alter_cuostomer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_image',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
