# Generated by Django 4.2.4 on 2023-10-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_remove_category_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_image',
            new_name='product_image',
        ),
    ]
