# Generated by Django 4.2.4 on 2023-10-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_product_produ_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='produ_image',
        ),
    ]
