# Generated by Django 4.2.4 on 2023-10-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_user_type_remove_user_user_type_user_user_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_t',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='user_type',
        ),
    ]
