# Generated by Django 4.2.4 on 2023-11-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_rename_user_image_user_user_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_img',
            new_name='user_image',
        ),
    ]
